### ISSUE TITLE
postgresql-server 9.3 is installed while version is set to 9.4 on ubuntu 14.04

### ISSUE THREAD

**Issue by ramonskie** [hw-cookbooks/postgresql#302] opened 2015-11-10 15:17 UTC
from v3.4.18 this cookbook fails on ubuntu 14.04
we explicitly set the postgresql version to 9.4
and what happens from v3.4.18 and higher is that
postgresql-9.3 is installed and then wants to create the cluster with 9.4
```
export LC_ALL=C; /usr/bin/pg_createcluster --start 9.4 main
```
this behavior does not happen with v3.4.16

**Comment by ramonskie** [comment] 2015-11-11 10:08
strange thing is if i set the following in the kitchen file
```
attributes
  postgresql:
    version: '9.4'
```
it works

but if i set the following in the attributes file of my wrapper cookbook
```
default[:postgresql][:version]                  = '9.4'
```
it does not work

please note that this behavior only happens since 3.4.18

**Comment by slyness** [comment] 2015-11-11 17:45
Thanks. If you discover the root cause and open a pull request to develop that would be awesome. I will also try and look at this before the end of the week but can not guarantee my time will be available before Friday.

**Comment by ramonskie** [comment] 2015-11-12 10:33
i have been looking at it for the last 2 day's and browsing tru the commits from February
but can't find anything useful

**Comment by ramonskie** [comment] 2015-11-12 11:46
found it..
you are using derived attributes see
https://christinemdraper.wordpress.com/2014/10/06/avoiding-the-possible-pitfalls-of-derived-attributes/

**Comment by ramonskie** [comment] 2015-11-13 12:32
i thing i found the exact reason
since 3.4.18 the config version are placed in the attributes file
and before that it was defined in a recipe 
https://github.com/hw-cookbooks/postgresql/blob/v3.4.16/recipes/config_version.rb

**Comment by legal90** [comment] 2015-11-18 20:31
@ramonskie Yes, exactly. v3.4.16 is the only cookbook version which works fine.

**Comment by slyness** [comment] 2015-11-23 19:10
Thank you very much for digging into this. I will be working on correcting this and a couple of other issues this week.

**Comment by patcon** [comment] 2015-12-09 00:58
Same issue here :) https://github.com/afklm/jira/issues/60

**Comment by patcon** [comment] 2015-12-09 01:01
Pulling certain things into library functions should also solve this, as logic in libraries would be calculated at execution time (some long as "lazy {}" is appropriately in resources) :)

Here's an example from @legal90's cookbook (note the includes at the bottom to make these available):
https://github.com/parallels-cookbooks/confluence/blob/master/libraries/helpers.rb

**Comment by mvdkleijn** [comment] 2015-12-09 12:46
@slyness Understand you're busy but.. any idea when you expect a fix for this? :smile:

**Comment by slyness** [comment] 2015-12-09 17:16
This is top of the list for correcting for the next release. I can't commit to a release date but I can say that I'd hope to have something in place before 2016. \o/

**Comment by patcon** [comment] 2015-12-09 17:17
Thanks for your consideration! :)

**Comment by patcon** [comment] 2015-12-09 17:21
Also, as part of this whole affair, it might be worth considering the splitting of pg gem install into another cookbook, like mysql2_chef_gem cookbook does.

This was a code spike I was working on, but had to put aside before finishing:
https://github.com/blendedperspectives/chef-pg-chef-gem

mysql2_chef_gem now seems to rely on the fact that the mysql cookbook migrated to a "service resource" based approach, but its history should show that it also existed when the mysql cookbook was still using recipes (like we are now in postresql)

**Comment by erkki** [comment] 2015-12-15 10:50
Use attributes of higher precedence when setting the version, eg role/environment attributes.

**Comment by slyness** [comment] 2015-12-23 20:42
I'm making progress on this. Should have something for testing soon.

**Comment by slyness** [comment] 2016-01-04 23:42
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0

**Closed by slyness** 2016-01-04 23:42 UTC

**Comment by btobolaski** [comment] 2016-01-05 07:18
While it is now possible to install postrgresql 9.4 on ubuntu 14.04, I don't think that the behavior is quite what people will expect. In order to actually install 9.4, you need to modify all of these values to 9.4 instead of 9.3 https://github.com/hw-cookbooks/postgresql/blob/e6977358d761236f10e1d5359f546e45000291a8/attributes/default.rb#L135-L140

**Comment by legal90** [comment] 2016-01-05 07:54
@slyness Thank you! But these attributes are still affected by the problem of "derived attributes":
https://github.com/hw-cookbooks/postgresql/blob/v4.0.0/attributes/default.rb#L188-L192

I'd recommend to use libraries in order to calculate such values, like we did in `confluence` cookbook: https://github.com/parallels-cookbooks/confluence/blob/master/libraries/helpers.rb#L105-L116
If you like this idea, I could prepare a pull-request.

**Comment by patcon** [comment] 2016-01-05 23:49
+1 for @legal90 PR (i've seen that he knows how to address this sort of concern)

**Comment by slyness** [comment] 2016-01-06 19:36
Using a library to calculate those values was expressly removed from this version. Because those methods are evaluated at compile time and will lead to inconsistent attribute evaluation and assignment. I don't feel that it is the correct way to resolve this type of dilemma.

I do agree that that `if`statement in the attribute files is still ugly and should be addressed more clearly in a future release but I do not feel that using a library method in this scenario is appropriate.

**Comment by legal90** [comment] 2016-02-19 08:52
@slyness 
> Because those methods are evaluated at compile time and will lead to inconsistent attribute evaluation and assignment

Could you please give an example of the case when such inconsistency occurs? We widely use evaluations via libraries and don't have any problems with that.
Thank you.

**Comment by patcon** [comment] 2016-02-19 18:28
I forgot to reply, but with all due respect, I believe you've got it backwards @slyness, and derived attributes are the greater evil :)

From browsing all these threads, it seems there was [only one person who experienced an issue](https://github.com/hw-cookbooks/postgresql/pull/231#issuecomment-92938998), and they reported it transiently on IRC, so we can't even follow up and confirm they weren't doing something else wonky or non-standard. And since that time, I'm counting at least 5 independent folks who've come forward to say the *current* approach has caused them some grief that they've had to work around in non-standard ways.

Related question: Are you guys running test-kitchen integration tests regularly? If so, perhaps I could submit a failing test suite (with version set in an attribute file or recipe, rather than in kitchen.yml) and if you find it to be reasonable that that suite succeed, then we could perhaps consider using library methods?

**Comment by luckymike** [comment] 2016-02-19 18:33
@patcon we do run test-kitchen on everything, and expect all releases to pass the available test suites. If you can submit a PR with a failing test-suite that covers the functionality that would be welcome as a away to investigate further.

**Comment by patcon** [comment] 2016-02-19 18:34
:+1: rockin. i'll try to get to that before I go vacay this weekend. thanks!

**Comment by chadwilken** [comment] 2016-03-17 21:34
Any update on this? I am trying to upgrade from 9.3 to 9.4 and am unable to do so.
