### ISSUE TITLE
postgresql::ruby - chef_gem[pg] install fails on missing gcc (Amazon Linux)

### ISSUE THREAD

**Issue by eric-tucker** [hw-cookbooks/postgresql#203] opened 2014-10-27 15:47 UTC
Manually installing gcc makes the cookbook work again.

Stacktrace from failed run:

````
Compiling Cookbooks...
[2014-10-27T15:37:48+00:00] INFO: WindowsPackage lightweight resource already initialized -- overriding!
Recipe: postgresql::client
  * package[postgresql-devel] action install[2014-10-27T15:37:49+00:00] INFO: Processing package[postgresql-devel] action install (postgresql::client line 31)
 (up to date)
Recipe: postgresql::ruby
  * chef_gem[pg] action install[2014-10-27T15:37:58+00:00] INFO: Processing chef_gem[pg] action install (postgresql::ruby line 55)

    
    ================================================================================
    Error executing action `install` on resource 'chef_gem[pg]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
    STDOUT: Building native extensions.  This could take a while...
    STDERR: ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.
    
            /opt/chef/embedded/bin/ruby extconf.rb
    checking for pg_config... yes
    Using config values from /usr/bin/pg_config
    checking for libpq-fe.h... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of
    necessary libraries and/or headers.  Check the mkmf.log file for more
    details.  You may need configuration options.
    
    Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
    /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:506:in `try_cpp'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:983:in `block in find_header'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:982:in `find_header'
        from extconf.rb:48:in `<main>'
    
    
    Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1 for inspection.
    Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1/ext/gem_make.out
    ---- End output of /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" ----
    Ran /opt/chef/embedded/bin/gem install pg -q --no-rdoc --no-ri -v "0.17.1" returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
    /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb
    
     55:     chef_gem "pg"
     56:   rescue Gem::Installer::ExtensionBuildError, Mixlib::ShellOut::ShellCommandFailed => e
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'
    
    chef_gem("pg") do
      provider Chef::Provider::Package::Rubygems
      action :install
      retries 0
      retry_delay 2
      guard_interpreter :default
      package_name "pg"
      version "0.17.1"
      timeout 900
      gem_binary "/opt/chef/embedded/bin/gem"
      cookbook_name "postgresql"
      recipe_name "ruby"
    end
    
[2014-10-27T15:38:03+00:00] WARN: Failed to properly build pg gem. Forcing properly linking and retrying (omnibus fix)
  * execute[generate pg gem Makefile] action run[2014-10-27T15:38:03+00:00] INFO: Processing execute[generate pg gem Makefile] action run (postgresql::ruby line 86)

    
    ================================================================================
    Error executing action `run` on resource 'execute[generate pg gem Makefile]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb ----
    STDOUT: checking for pg_config... yes
    STDERR: Using config values from /usr/bin/pg_config
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of
    necessary libraries and/or headers.  Check the mkmf.log file for more
    details.  You may need configuration options.
    
    Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
    /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
        from extconf.rb:52:in `<main>'
    ---- End output of PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb ----
    Ran PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:92:in `rescue in rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:54:in `rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
    /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb
    
     86:     lib_builder = execute 'generate pg gem Makefile' do
     87:       # [COOK-3490] pg gem install requires full path on RHEL
     88:       command "PATH=$PATH:/usr/pgsql-#{node['postgresql']['version']}/bin #{RbConfig.ruby} extconf.rb"
     89:       cwd ext_dir
     90:       action :nothing
     91:     end
     92:     lib_builder.run_action(:run)
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:86:in `rescue in rescue in from_file'
    
    execute("generate pg gem Makefile") do
      action [:nothing]
      retries 0
      retry_delay 2
      guard_interpreter :default
      command "PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb"
      backup 5
      cwd "/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/pg-0.17.1/ext"
      returns 0
      cookbook_name "postgresql"
      recipe_name "ruby"
    end
    
  
  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/database/recipes/postgresql.rb
  ================================================================================
  
  Mixlib::ShellOut::ShellCommandFailed
  ------------------------------------
  execute[generate pg gem Makefile] (postgresql::ruby line 86) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
  ---- Begin output of PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb ----
  STDOUT: checking for pg_config... yes
  STDERR: Using config values from /usr/bin/pg_config
  *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of
  necessary libraries and/or headers.  Check the mkmf.log file for more
  details.  You may need configuration options.
  
  Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
  /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
  You have to install development tools first.
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
        from extconf.rb:52:in `<main>'
  ---- End output of PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb ----
  Ran PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:92:in `rescue in rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:54:in `rescue in from_file'
    /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:21:in `from_file'
    /var/chef/cache/cookbooks/database/recipes/postgresql.rb:20:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/postgresql/recipes/ruby.rb:
  
   85:  
   86:      lib_builder = execute 'generate pg gem Makefile' do
   87:        # [COOK-3490] pg gem install requires full path on RHEL
   88:        command "PATH=$PATH:/usr/pgsql-#{node['postgresql']['version']}/bin #{RbConfig.ruby} extconf.rb"
   89:        cwd ext_dir
   90:        action :nothing
   91:      end
   92>>     lib_builder.run_action(:run)
   93:  
   94:      lib_maker = execute 'make pg gem lib' do
   95:        command 'make'
   96:        cwd ext_dir
   97:        action :nothing
   98:      end
   99:      lib_maker.run_action(:run)
  100:  
  101:      lib_installer = execute 'install pg gem lib' do
  
  
  Running handlers:
[2014-10-27T15:38:03+00:00] ERROR: Running exception handlers
  Running handlers complete
[2014-10-27T15:38:03+00:00] ERROR: Exception handlers complete
[2014-10-27T15:38:03+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 0 resources updated in 16.680772034 seconds
[2014-10-27T15:38:03+00:00] ERROR: execute[generate pg gem Makefile] (postgresql::ruby line 86) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb ----
STDOUT: checking for pg_config... yes
STDERR: Using config values from /usr/bin/pg_config
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
/opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
        from extconf.rb:52:in `<main>'
---- End output of PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb ----
Ran PATH=$PATH:/usr/pgsql-9.0/bin /opt/chef/embedded/bin/ruby extconf.rb returned 1
[2014-10-27T15:38:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
````

**Comment by ambientsound** [comment] 2015-01-27 09:28
Duplicate of #212 ?

**Comment by bplunkert** [comment] 2015-03-13 04:57
Not sure, but I was missing gcc and automake. PR #237 fixes this for me.

**Comment by tas50** [comment] 2016-10-06 03:15
I believe this is due to an old version of build-essential. I created a PR with better pin of the build-essential cookbook, but bringing in the latest and greatest will probably resolve this.

**Comment by tas50** [comment] 2016-10-06 03:15
PR is #365  btw

**Closed by tas50** 2016-10-06 03:15 UTC
